name: Test
permissions: write-all
on:
  push:
    branches: [ main ]
    paths:
      - "terraform/**"
  pull_request:
    paths:
      - "terraform/**"  
  workflow_dispatch:
jobs:
  production-terraform:
    uses: Aatishsharma77/GithubAction-Demo/.github/workflows/terraform_workflow.yml@main
    with:
        provider:            aws
        working_directory:  "terraform/**"
        aws_region:         eu-west-1
        terraform_version:  1.6.4
        destroy:            false
        timeout:            2
    secrets:
        BUILD_ROLE: ${{ secrets.TEST }}
